# apache with fcgi enabled, intended to answer to requests for
# mediawiki-related stuff, so, wiki pages, mediawiki api requests
# and so on

FROM wikimedia-dumps/base:latest

RUN apt-get install -y apache2 libapache2-mod-security2 && \
    mkdir -p /run/apache2 /var/lock/apache2 /var/log/apache2 && chown www-data:www-data /run/apache2 /var/lock/apache2 /var/log/apache2

COPY "httpd/" "/root/"

EXPOSE 22
CMD /usr/sbin/sshd -D
