# php-fpm final image with set info

FROM wikimedia-dumps/phpfpm-base:latest
ARG SETNAME

# we want the file with all the container names for the set; these will
# be embedded in various files in the image
COPY ["phpfpm/substitution.conf", "container_list.$SETNAME", "credentials.$SETNAME.yaml", "/root/"]
RUN python3 /root/setup_image.py --stage final --type phpfpm --set "$SETNAME"

# ports for sshd, phpfpm
EXPOSE 22 9000

# fixme add phpfpm crapola later
CMD /usr/sbin/sshd -D

